### ISSUE TITLE
[BUG] `cannot import name 'PYZ_TYPE_PKG' from 'PyInstaller.loader.pyimod01_archive' (C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\loader\pyimod01_archive.py)`

### ISSUE THREAD

**Issue by kr1tx** [dashingsoft/pyarmor#1228]
Works with pyinstaller 5.9.0 but doesnt work with pyinstaller 5.10.1
```
$ pyarmor gen -e 2023-07-20 --enable-bcc --enable-jit --mix-str --assert-call --assert-import --private --pack dist\Script.exe Script.py
INFO     Python 3.10.8
INFO     Pyarmor 8.1.9 (pro), xxxxxx, non-profits
INFO     Platform windows.x86_64

```

**Comment by jondy** [comment]
duplicated #1215
