### ISSUE TITLE
 Check restrict mode failed, did not modify anything in my obf'd file

### ISSUE THREAD

**Issue by kekermen** [dashingsoft/pyarmor#81]
I read that usually the " Check restrict mode failed " happens when you modify the obf'd file. However, I did not change anything in my obfuscated file but it still happens. I've tried downgrading to a lower version, but get a host of other problems.

```python
from pytransform import pyarmor_runtime
pyarmor_runtime()
__pyarmor__(__name__, __file__, b'\xff\x50\x8c\x64\x26\x42\xd6\x01\x64\x00\x3f\xba\x09\x54\x3d\x0c\x49\xeb\xd0\x5a\x7e\xd8\x3d\xbb\xa0\x54\x44\xc6\x18\xe7\x16\x3c\xdc\xbe\x1a\x1b\x95\x30\x73\xb7\xbb\x7f\x15\x32\xee\xf4\ etc etc
```

Any fix/reason it would be doing this?

pyarmor==5.3.9

**Comment by jondy** [comment]
First try to disable restrict mode, use undocument option `--restrict`, for example,
```
pyarmor obfuscate --restrict 0 foo.py
cd dist
python foo.py
```

And what about the output of following script:
```
python -c "with open('your_obfuscated_scipt_file_name.py') as f:
  s = f.read()
co = compile(s, '<frozen pyarmor>', 'exec')
print('code length is %d' % len(co.co_code))"
```

**Comment by kekermen** [comment]
> First try to disable restrict mode, use undocument option `--restrict`, for example,
> 
> ```
> pyarmor obfuscate --restrict 0 foo.py
> cd dist
> python foo.py
> ```
> 
> And what about the output of following script:
> 
> ```
> python -c "with open('your_obfuscated_scipt_file_name.py') as f:
>   s = f.read()
> co = compile(s, '<frozen pyarmor>', 'exec')
> print('code length is %d' % len(co.co_code))"
> ```

I got an output of 36

**Comment by jondy** [comment]
The code length is right, it's strange because it's the only checkpoint for restrict mode in v5.3.9. 

Does it work if restrict mode is disabled?

**Comment by kekermen** [comment]
> The code length is right, it's strange because it's the only checkpoint for restrict mode in v5.3.9.
> 
> Does it work if restrict mode is disabled?

Nope, tried both, do you want the obf'd py file, or is there no option but to roll back?

However if I roll back to versions before 5.0.1, any exterior module causes error, throwing the exception
"module X is not found"

**Comment by jondy** [comment]
If you have old pyarmor version installed, you'd better to obfuscate all the scripts again after upgrading to v5.3.9. 

Try to obfuscate a single simple .py file by v5.3.9
```
rm -rf dist
pyarmor obfuscate foo.py
cd dist
python foo.py
```

If it still doesn't work, pack all the files in the path `dist` and upload it here.

**Comment by kekermen** [comment]
Had everything updated, packed and zipped it

Still getting restrict error

https://www.sendspace.com/file/lxdawv

**Comment by jondy** [comment]
Sorry I can't open this link. Could you drag and drop the zipped file here?

BTW, what's the output of `uname -a` in target machine?

**Comment by kekermen** [comment]
Github doesnt support rars tell me a mirror you prefer,

doing `uname -a` results in "'uname' is not recognized as an internal or external command"

**Comment by jondy** [comment]
Does you obfuscate the scripts and run the obfuscated script by same python? If not, to be sure that the major version of Python in build machine is same as in target machine.

https://pyarmor.readthedocs.io/en/latest/differences.html#the-differences-of-obfuscated-scripts

If the major version of Python is same, just upload .zip file here. Github support zip file

If `uname` doesn't work, what's the output of this command:
```
python -c'import os
print(os.uname())'
```

**Comment by kekermen** [comment]
[dist.zip](https://github.com/dashingsoft/pyarmor/files/3214376/dist.zip)

AttributeError: module 'os' has no attribute 'uname'

**Comment by jondy** [comment]
What's your OS and version? and What's python version to run and obfuscated python scripts?

**Comment by jondy** [comment]
I download  the `dist.zip`, unfortunately it can't be unzipped. It seems the file doesn't uploaded completely.

And the file I have downloaded is about 11M bytes, generally the runtime files and one simple obfuscated scripts should not no more than 2M. Why is it so big? Do you obfuscate the python system library either?

**Comment by kekermen** [comment]
[Test.zip](https://github.com/dashingsoft/pyarmor/files/3214463/Test.zip)

I usually Obfuscate my .py program, then PACK, which shows an error.

Im running windows64 bit, to the newest version (10.0.17134 Build 17134)

**Comment by jondy** [comment]
And could you show the output of the following obfuscating command, suppose pyamor is installed in the path `/path/to/pyarmor`:
```
pyarmor obfuscate --restrict 0 /path/to/pyarmor/examples/simple/queens.py
cd dist
python queens.py
```

**Comment by kekermen** [comment]
```
INFO     PyArmor Trial Version 5.3.9

INFO     Source path is "C:\Users\admin\Desktop\Test"
INFO     Entry script is a.py
INFO     Use cached capsule C:\Users\admin\.pyarmor_capsule.zip
INFO     Normal mode is on
INFO     Save obfuscated scripts to "dist"
INFO     Read public key from capsule
INFO     Obfuscate scripts with default mode
INFO            a.py -> dist\a.py
INFO     1 scripts have been obfuscated
INFO     Generating runtime files to dist
INFO     Extract pytransform.key
INFO     Extract license.lic
INFO     Copying c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\platforms\windows32\_pytransform.dll
INFO     Generate runtime files OK
INFO     Obfuscate scripts with restrict mode off
INFO     Generate no restrict mode license file: dist\license.lic
INFO     Insert bootstrap code to entry script dist\a.py
INFO     Obfuscate 1 scripts OK.
```

**Comment by jondy** [comment]
What's the output of `pyarmor queens.py`?  Does it report "Check restrict mode failed"?

**Comment by kekermen** [comment]
nope ,it works, it shows errors only when I pack it.

**Comment by jondy** [comment]
Try to pass extra obfuscation options by `-x` to disable restrict mode for `pack` command:
```
pyarmor pack -x " --restrict 0” a.py
```

**Comment by kekermen** [comment]
That worked to get rid of restriction mode, but now getting

ModuleNotFoundError: No module named 'requests'
[9268] Failed to execute script a

thats interesting as requests is updated

**Comment by jondy** [comment]
This is because the module "requests" aren't packed into the bundle.

How about packing the original script "a.py"?
```
python -m PyInstaller a.py
cd dist/a
./a.exe
```

If it reports the same error, try to pass extra pack options:
```
pyarmor pack -x " --restrict 0" -e " --hidden-import requests" a.py
```

**Comment by kekermen** [comment]
well whats the point of packing the original script, if I use pyarmor for the obfuscation?
if you meant packing the OBFUSCATED script, it doesn't work, it shows the error 
`Could not find "C:\Users\admin\Desktop\Test\dist\dist\a\_pytransform.dll"`
adding files needed goes back to to the original problem

I have like 10 more imports to add, so how would I go about adding new imports?

**Comment by jondy** [comment]
PyArmor packs the scripts by calling PyInstaller, first I want to know whether PyInstaller could find all the dependent modules, so just pack the original script directly:
```
python -m PyInstaller a.py
cd dist/a
./a.exe
```
If it reports missing module, you need add them by option `--hidden-import`, for examples
```
python -m PyInstaller --hidden-import requests --hidden-import ctypes a.py
```

To be sure the bundle packed by original script works, then pack the obfuscated scripts by pyarmor
```
pyarmor pack -x " --restrict 0" -e " --hidden-import requests --hidden-import ctypes" a.py
```

**Comment by kekermen** [comment]
Doing just pyinstaller works, however, OBFUSCATING the file first, then pyinstaller / PACK option doesn't work no matter what I do. some modules are fine like REQUESTS but others like ctypes cause issues like these. If no fix, somethings probably wrong on my part, do you think it could have anything to do with my machine? 

```
line 531, in assemble
    ctypes_code_objs = self.graph.get_co_using_ctypes()  # dict like:  {'module1': code_obj, 'module2': code_obj}
  File "c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 554, in get_co_using_ctypes
    r_ident =  r.identifier
AttributeError: 'NoneType' object has no attribute 'identifier'
```
example error, probably an error on pyinstallers part

**Comment by jondy** [comment]
Hi guy, I think I found the problem. 

Do not pack the obfuscated scripts, but pack it directly, for example,
```
pyarmor pack a.py
```
Here `a.py` is the plain script, it should not be obfuscated. The command `pack` will obfuscate it automatically.

**Comment by kekermen** [comment]
H O L Y H E C K

thanks so much <3
