### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode' in plugin check_ntp_time [BUG]

### ISSUE THREAD

**Issue by kr1tx** [dashingsoft/pyarmor#1031]
So I tried `pyarmor-7 pack --with-license licenses\new1\license.lic -x " --advanced 5 --plugin check_ntp_time" -e " --onefile --icon fuse.ico" Script.py` and got the following what is on line 2 is `# {PyArmor Plugins}`, any help?
```
E:>Program.exe
Traceback (most recent call last):
  File "<frozen Program>", line -1, in spp_caller
AttributeError: module 'pytransform' has no attribute '_pytransform'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<dist\obf\Program.py>", line 2, in <module>
  File "<frozen Program>", line 487, in <module>
  File "<frozen Program>", line 487, in <module>
  File "<frozen Program>", line -1, in spp_caller
  File "<frozen Program>", line -1, in spp_caller
  File "<frozen Program>", line -1, in spp_caller
  File "<frozen Program>", line -1, in spp_caller
AttributeError: 'NoneType' object has no attribute 'decode'
[3764] Failed to execute script 'Program' due to unhandled exception!
```
**Note that it works well with PyArmor Version 7.7.4!**
**Edit** I uninstalled PyArmor 8 and downgraded back to 7.7.4, And got the same error.

**Comment by kr1tx** [comment]
NVM I just generated a license in a wrong way.
