### ISSUE TITLE
[BUG] Error when obfuscating code using bcc || mix-str. 

### ISSUE THREAD

**Issue by crasyjoel** [dashingsoft/pyarmor#1040]
**When I run this command: pyarmor gen -O dist C:\Users\xx\Documents\xx\packs, it works with no probelms.
When I run this command: pyarmor gen -O dist --enable-bcc C:\Users\xx\Documents\xx\packs, it failed with:**
3060 MainProcess 2023-03-28 23:00:07,758
Traceback (most recent call last):
  File "C:\Users\xx\Documents\xx\venv\lib\site-packages\pyarmor\cli\__main__.py", line 576, in main
    main_entry(sys.argv[1:])
  File "C:\Users\xx\Documents\xx\venv\lib\site-packages\pyarmor\cli\__main__.py", line 564, in main_entry
    args.func(ctx, args)
  File "C:\Users\xx\Documents\xx\venv\lib\site-packages\pyarmor\cli\__main__.py", line 152, in cmd_gen
    builder.process(options, pack=args.pack)
  File "C:\Users\xx\Documents\xx\venv\lib\site-packages\pyarmor\cli\generate.py", line 153, in process
    self._obfuscate_scripts()
  File "C:\Users\xx\Documents\xx\venv\lib\site-packages\pyarmor\cli\generate.py", line 118, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
  File "C:\Users\xx\Documents\xx\venv\lib\site-packages\pyarmor\cli\core\__init__.py", line 48, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
  File "<maker>", line 714, in generate_obfuscated_script
  File "<maker>", line 504, in process
  File "<maker>", line 504, in <listcomp>
  File "<bccmaker>", line 875, in process
  File "<bccmaker>", line 660, in build
  File "C:\Users\xx\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\xx\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\xx\\.pyarmor\\clang.exe', '-O3', '-Wno-unsequenced', '-fno-asynchronous-unwind-tables', '-fno-unwind-tables', '--target=x86_64-elf-windows', '-c', '-o', '.pyarmor/bcc\\packs.ITAC.Model.Model_ITAC_RAFITS_05.c.o', '.pyarmor/bcc\\packs.ITAC.Model.Model_ITAC_RAFITS_05.c']' returned non-zero exit status 1.

**When I run this command: pyarmor gen -O dist --enable-bcc C:\Users\xx\Documents\xx\packs, it successfully generated but failed with run:**
(venv) PS C:\Users\xx\Documents\xx\dist\packs> python .\Controller_Task_Main_Load.py
Traceback (most recent call last): 
  File "<frozen __main__>", line 3, in <module> 
  File "<frozen packs.Controller_Task_Main_Load>", line 7, in <module>
  File "C:\Users\xx\Documents\ita_final_v1_20230105\venv\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen IT_Understanding.Controller.Controller_IT_Understanding_01_project_info>", line 3, in <module>
  File "<frozen packs.IT_Understanding.Controller.Controller_IT_Understanding_01_project_info>", line 5, in <module>
  File "C:\Users\xx\Documents\ita_final_v1_20230105\venv\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen General.Model.M_Func_Save>", line 3, in <module>
  File "<frozen packs.General.Model.M_Func_Save>", line 5, in <module>
  File "C:\Users\xx\Documents\ita_final_v1_20230105\venv\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen IT_Understanding.Model.Model_IT_Understanding_Mapping>", line 3, in <module>
  File "<frozen packs.IT_Understanding.Model.Model_IT_Understanding_Mapping>", line 8, in <module>
  File "C:\Users\xx\Documents\ita_final_v1_20230105\venv\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen IT_Understanding.Model.Model_Tables.Model_IT_understanding_tables>", line 3, in <module>
  File "<frozen packs.IT_Understanding.Model.Model_Tables.Model_IT_understanding_tables>", line 2, in <module>
  File "C:\Users\xx\Documents\ita_final_v1_20230105\venv\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen IT_Understanding.Model.Model_Tables.Model_Parameters_table>", line 3, in <module>
  File "<frozen packs.IT_Understanding.Model.Model_Tables.Model_Parameters_table>", line 8, in <module>
  File "<frozen packs.IT_Understanding.Model.Model_Tables.Model_Parameters_table>", line 9, in Industry_Sector
NameError: name '__assert_armored__' is not defined

**Comment by jondy** [comment]
Could you share `Industry_Sector` function?

Also check this command in the console, before that make sure file `.pyarmor\bcc\packs.ITAC.Model.Model_ITAC_RAFITS_05.c` exists
```
C:\Users\xx\.pyarmor\clang.exe --target=x86_64-elf-windows -c .pyarmor\bcc\packs.ITAC.Model.Model_ITAC_RAFITS_05.c
```

**Comment by crasyjoel** [comment]
**Could you share Industry_Sector function?**（Sqlalchemy）

`class Industry_Sector:

    def __init__(self, session):
        self.session = session

    def get_All(self):
        result = self.session.query(Industry_Sector_database).all()
        li_tmp = list()
        for ele in result:
            li_tmp.append(
                [ele.Identify, ele.Industry, ele.Sector, ele.Executor, ele.Reviewer, ele.Execute_time, ele.Review_time])
        df = pd.DataFrame(li_tmp)
        if len(df) != 0:
            df.columns = ['identify', 'Industry', 'Sector', 'Executor', 'Reviewer', 'Execute_time', 'Review_time']
        return df

    def del_row_with_id(self, index_id):
        index_id = str(index_id)
        delete_row = self.session.query(Industry_Sector_database).filter(
            Industry_Sector_database.Identify == index_id).delete()
        self.session.commit()

    def set_values(self, list_values):  # flag区分是否重新生成uuid
        s = Industry_Sector_database()
        s.Identify = str(uuid.uuid1())
        s.Industry = list_values[1]
        s.Sector = list_values[2]
        s.Executor = list_values[3]
        s.Reviewer = list_values[4]
        s.Execute_time = list_values[5]
        s.Review_time = list_values[6]
        return s

    def add_rows(self, obj1):
        self.session.add(obj1)
        self.session.commit()

    def is_null(self):
        if len(self.get_All()) != 0:
            return False
        else:
            return True
`

`class Industry_Sector(Base):

    __tablename__ = r'Industry&Sector'

    Sector = Column('Sector', String, primary_key=True)
    Industry = Column('Industry', String) #, primary_key=True)`

**Also check this command in the console, before that make sure file .pyarmor\bcc\packs.ITAC.Model.Model_ITAC_RAFITS_05.c exists**

(venv) PS C:\Users\XX\Documents\ita_final_v1_20230328> C:\Users\XX\.pyarmor\clang.exe --target=x86_64-elf-windows -c .pyarmor\bcc\packs.ITAC.Model.Model_ITAC_RAFITS_05.c
.pyarmor\bcc\packs.ITAC.Model.Model_ITAC_RAFITS_05.c:445:72: warning: multiple unsequenced modifications to 'x' [-Wunsequenced]
      if (wr_value(&(f_vars[5]), ld_item(ld_value(f_vars[5]), op_and((x=op_compare(f_vars, PyCmp_NE, ld_item(ld_value(f_vars[5]), ld_value(m_consts[5])), ld_value(m_consts[6])),t=(x?PyObject_IsTrue(x):-1),t<0) ? NULL : (t?(x):ld_value(Py_False)), (x=op_compare(f_vars, PyCmp_NE, ld_item(ld_value(f_vars[5]), ld_value(m_consts[5])), ld_value(m_consts[7])),t=(x?PyObject_IsTrue(x):-1),t<0) ? NULL : (t?(x):ld_value(Py_False)...     
                                                                       ^                                                                                                                                                                                 ~
.pyarmor\bcc\packs.ITAC.Model.Model_ITAC_RAFITS_05.c:163:40: note: expanded from macro 'op_and'
#define op_and(a, b)         op_binary(a, b, Py_nb_and)
                                       ^  ~
.pyarmor\bcc\packs.ITAC.Model.Model_ITAC_RAFITS_05.c:445:179: warning: multiple unsequenced modifications to 't' [-Wunsequenced]
      if (wr_value(&(f_vars[5]), ld_item(ld_value(f_vars[5]), op_and((x=op_compare(f_vars, PyCmp_NE, ld_item(ld_value(f_vars[5]), ld_value(m_consts[5])), ld_value(m_consts[6])),t=(x?PyObject_IsTrue(x):-1),t<0) ? NULL : (t?(x):ld_value(Py_False)), (x=op_compare(f_vars, PyCmp_NE, ld_item(ld_value(f_vars[5]), ld_value(m_consts[5])), ld_value(m_consts[7])),t=(x?PyObject_IsTrue(x):-1),t<0) ? NULL : (t?(x):ld_value(Py_False)...     
                                                                                                                                                                                  ^                                                                                                                                                                                 ~
.pyarmor\bcc\packs.ITAC.Model.Model_ITAC_RAFITS_05.c:163:40: note: expanded from macro 'op_and'
#define op_and(a, b)         op_binary(a, b, Py_nb_and)
                                       ^  ~
.pyarmor\bcc\packs.ITAC.Model.Model_ITAC_RAFITS_05.c:1126:93: error: use of undeclared identifier 'None'
    if (wr_value(&(f_vars[5]), ld_item(ld_attr(ld_value(f_vars[5]), ld_value(m_consts[0])), None)) != 0) break;
                                                                                            ^
2 warnings and 1 error generated.

**Comment by jondy** [comment]
I have fixed `--mix-str` issue in 8.0.25
But for `--enable-bcc` issue, still not. But in 8.0.25, it will report which line fails. Please test it with 8.0.25, and report the line content, thanks.

**Comment by crasyjoel** [comment]
**Really appreciate fixing issues. When I upgrade to 8.0.25, both mix-str and bcc successfully generated, but all runs with same issue:**

(venv) PS C:\Users\xx\Documents\ita_final_v1_20230328\dist\packs> python .\Controller_Task_Main_Load.py
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen packs.Controller_Task_Main_Load>", line 7, in <module>
  File "C:\Users\xx\Documents\ita_final_v1_20230105\venv\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen IT_Task.View.View_Task_Menu_Bar>", line 3, in <module>
  File "<frozen packs.IT_Task.View.View_Task_Menu_Bar>", line 12, in <module>
  File "C:\Users\xx\Documents\ita_final_v1_20230105\venv\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen IT_Task.Controller.Controller_Task_General_Member>", line 3, in <module>                                                                                                                                                                                                                                                                                            
  File "<frozen packs.IT_Task.Controller.Controller_Task_General_Member>", line 21, in <module>
  File "C:\Users\xx\Documents\ita_final_v1_20230105\venv\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen ITGC.Model.Model_ITGC_Generator>", line 3, in <module>
IndexError: tuple assignment index out of range
