### ISSUE TITLE
AttributeError: module 'pytransform_xxx_xxxx' has no attribute 'sys'

### ISSUE THREAD

**Issue by venugopalnaiduch** [dashingsoft/pyarmor#539]
Error in executing encrypted code if sys module is loaded in the code with runtime library

I have created a simple code test.py

**import sys
if __name__ == "__main__":
        print(sys.argv)
        print('HI')**
   
pyarmor runtime --enable-suffix --advanced 2 -O pyarmor_runtime
pyarmor obfuscate --runtime pyarmor_runtime test.py
python3.9 dist/test.py 

Using pyarmor latest verison 6.7.3 and also tried with dev version 6.7.4
The same code working fine with python3.6 with --advanced 1

![image](https://user-images.githubusercontent.com/86103380/125081084-39fcd100-e0e3-11eb-9276-eceaf4d6569c.png)

Thanks In Advance.

**Comment by jondy** [comment]
It's a bug. A quick workaround is to make runtime with extra option `--super-mode`, for example
```
pyarmor runtime --enable-suffix --advanced 2 --super-mode -O pyarmor_runtime
```

Or use pre-release version v6.7.4 (It applies this patch a5b1cb06ad02702e74538114709c3f9c74f5917f)

**Comment by venugopalnaiduch** [comment]
Thanks for the quick response, with --super-mode it is working
