### ISSUE TITLE
cannot pack with pyinstaller 6

### ISSUE THREAD

**Issue by kletel** [dashingsoft/pyarmor#1516]
Hi,
I am using Pyarmor 8.3.10 (pro) with a licence
It's not working with pyinstaller 6.0.0

pyinstaller --clean --noconfirm --windowed --onedir myapp.py

pyarmor gen -O obfdist --pack dist\myapp\myapp.exe myapp.py

ERROR    ZlibArchiveWriter.__init__() got an unexpected keyword argument 'cipher'

it's working with pyinstaller 5.13.2

**Comment by jondy** [comment]
Please check documentation `insight into pack command` and use the second method to pack obfuscated manually first.

About supporting Pyinstaller 6.0.0 is not in schedule.

**Comment by jondy** [comment]
I have tested a simple script with pyinstaller 6.0.0, the second method
https://pyarmor.readthedocs.io/en/latest/topic/repack.html#packing-obfuscated-scripts-manually
works, just use an extra option `--clean` when building final bundle

**Comment by kletel** [comment]
ok thank you
